location_dictionaries: dict = {"Abu al Bukhoosh": "AEABU", "Ajman": "AEAJM",
                               "Abu Dhabi": "AEAUH",
                               "Dubai": "AEDXB",
                               "Al Fujayrah": "AEFJR",
                               "Jebel Ali": "AEJEA",
                               "Jebel Dhanna": "AEJED",
                               "Mina Khalifa/Abu Dhabi": "AEKHL",
                               "Khor al Fakkan": "AEKLF",
                               "Mina Rashid Port": "AEMRP",
                               "Umm al Qaiwain": "AEQIW",
                               "Jebel Ali Free Zone": "AEQWE",
                               "Ras al Khaimah": "AERKT",
                               "Sharjah": "AESHJ",
                               "Antigua": "AGANU",
                               "Saint John's": "AGSJO",
                               "Blowing Point": "AIBLP",
                               "Road Bay": "AIRBY",
                               "Durres": "ALDRZ",
                               "Tirana": "ALTIA",
                               "Yerevan": "AMEVN",
                               "Cabinda": "AOCAB",
                               "Luanda": "AOLAD",
                               "Lobito": "AOLOB",
                               "Namibe": "AOMSZ",
                               "Soyo": "AOSZA",
                               "Bahia Blanca": "ARBHI",
                               "Buenos Aires": "ARBUE",
                               "Las Palmas": "ARLPS",
                               "Mar del Plata": "ARMDQ",
                               "Puerto Madryn": "ARPMY",
                               "Puerto Borghi": "ARPUB",
                               "Puerto Deseado": "ARPUD",
                               "Rosario": "ARROS",
                               "San Lorenzo": "ARSLO",
                               "Ushuaia": "ARUSH",
                               "Zarate": "ARZAE",
                               "Pago Pago": "ASPPG",
                               "Fischamend Dorf": "ATFIS",
                               "Wien": "ATVIE",
                               "Adelaide": "AUADL",
                               "Barry Beach": "AUBAR",
                               "Bell Bay": "AUBEL",
                               "Brisbane": "AUBNE",
                               "Burnie": "AUBWT",
                               "Dampier": "AUDAM",
                               "Devonport": "AUDPO",
                               "Darwin": "AUDRW",
                               "Fremantle": "AUFRE",
                               "Glebe Island": "AUGLL",
                               "Gladstone": "AUGLT",
                               "Greenock": "AUGRK",
                               "Hobart": "AUHBA",
                               "Launceston": "AULST",
                               "Melbourne": "AUMEL",
                               "Newcastle": "AUNTL",
                               "Port Adelaide": "AUPAE",
                               "Perth": "AUPER",
                               "Port Hedland": "AUPHE",
                               "Port Kembla": "AUPKL",
                               "Sydney": "AUSYD",
                               "Townsville": "AUTSV",
                               "Aruba": "AWAUA",
                               "Barcadera": "AWBAR",
                               "Oranjestad": "AWORJ",
                               "Baku": "AZBAK",
                               "Sarajevo": "BASJJ",
                               "Bridgetown": "BBBGI",
                               "Chittagong": "BDCGP",
                               "Mongla": "BDMGL",
                               "Pangaon": "BDPGN",
                               "Antwerpen": "BEANR",
                               "Bruxelles (Brussel)": "BEBRU",
                               "Geel": "BEGEL",
                               "Gent (Ghent)": "BEGNE",
                               "Havre": "BEHRE",
                               "Kallo": "BEKOU",
                               "Meer": "BEMEE",
                               "Meerhout": "BEMEH",
                               "Neder-Over-Heembeek": "BENVH",
                               "Rekkem": "BEREK",
                               "Tessenderlo": "BETES",
                               "Thorembais-les-Beguines": "BETRG",
                               "Zeebrugge": "BEZEE",
                               "Burgas": "BGBOJ",
                               "Plovdiv": "BGPDV",
                               "Sofia": "BGSOF",
                               "Varna": "BGVAR",
                               "Bahrain": "BHBAH",
                               "Khalifa Bin Salman Port": "BHKBS",
                               "Manama": "BHMAN",
                               "Cotonou": "BJCOO",
                               "Gustavia": "BLGUS",
                               "Hamilton": "BMBDA",
                               "Freeport": "BMFPT",
                               "Southampton": "BMSOU",
                               "Muara": "BNMUA",
                               "Kralendijk": "BQKRA",
                               "Saba": "BQSAB",
                               "Belem": "BRBEL",
                               "Fortaleza": "BRFOR",
                               "Imbituba": "BRIBB",
                               "Itaguai": "BRIGI",
                               "Itapoa": "BRIOA",
                               "Itajai": "BRITJ",
                               "Manaus": "BRMAO",
                               "Natal": "BRNAT",
                               "Navegantes": "BRNVT",
                               "Pecem": "BRPEC",
                               "Paranagua": "BRPNG",
                               "Porto Velho": "BRPVH",
                               "Recife": "BRREC",
                               "Rio Grande": "BRRIG",
                               "Rio de Janeiro": "BRRIO",
                               "Sepetiba": "BRSEP",
                               "Port of Itaguai": "BRSPB",
                               "Salvador": "BRSSA",
                               "Santos": "BRSSZ",
                               "Suape": "BRSUA",
                               "Vila do Conde Pt/Barcarena": "BRVDC",
                               "Vitoria": "BRVIT",
                               "Vitoria": "BRVIX",
                               "Vila do Conde": "BRVLC",
                               "Freeport": "BSFPO",
                               "Marin": "BSNAS",
                               "Bitung": "BSOCE",
                               "Belawan": "BYMSQ",
                               "Jambi": "BZBGK",
                               "Jakarta": "BZBZE",
                               "Medan": "CAHAL",
                               "Merauke": "CAHAM",
                               "Merak": "CAKIN",
                               "Panjang (Lampung": "CAMNT",
                               "Palembang": "CAMRE",
                               "Fukuyama": "CAMTR",
                               "Fukuyama": "CANWP",
                               "Kashima": "CAPRR",
                               "Miike": "CAQUE",
                               "Miike": "CASJB",
                               "Naha": "CASJF",
                               "Nagoya": "CASYD",
                               "Nagoya": "CATRR",
                               "Sendai": "CAVAN",
                               "Sendai": "CAWNP",
                               "Tamatsu": "CDBOA",
                               "Mutsamudu": "CDFIH",
                               "Basseterre": "CDMAT",
                               "Georgetown": "CFTOG",
                               "Kota Kinabalu": "CGPNR",
                               "Bintulu": "CHBSL",
                               "Kuching": "CIABJ",
                               "Labuan": "CISPY",
                               "Miri": "CKAIT",
                               "Pasir Gudang": "CKRAR",
                               "Sibu": "CLANF",
                               "Sandakan": "CLARI",
                               "Tawau": "CLCHB",
                               "PanamÃ¡": "CLCNL",
                               "Cagayan de Oro": "CLIQQ",
                               "Davao": "CLLQN",
                               "Funchal": "CLMJS",
                               "Honiara": "CLPAG",
                               "Noro": "CLPCH",
                               "Road Town": "CLPMC",
                               "Charlotte Amalie": "CLPUQ",
                               "Christiansted": "CLSAI",
                               "San Vicente": "CLSVE",
                               "Talcahuano": "CLTAL",
                               "Valparaiso": "CLVAP",
                               "Osorno": "CLZOS",
                               "Douala": "CMDLA",
                               "Kribi": "CMKBI",
                               "Anqing": "CNAQG",
                               "Bayuquan": "CNBAY",
                               "Beihai Pt": "CNBHP",
                               "Beihai": "CNBHY",
                               "Beijiao": "CNBIJ",
                               "Guangzhou": "CNCAN",
                               "Changde": "CNCDE",
                               "Chengdu": "CNCDU",
                               "Zhengzhou": "CNCGO",
                               "Changchun": "CNCGQ",
                               "Chenghai Laiwu": "CNCGS",
                               "Changshu": "CNCGU",
                               "Civet / Guandong": "CNCIV",
                               "Chongqing": "CNCKG",
                               "Changsha": "CNCSX",
                               "Chiwan": "CNCWN",
                               "Changzhou": "CNCZX",
                               "Dalian": "CNDAL",
                               "Da Chan Bay": "CNDCB",
                               "Dafeng": "CNDFE",
                               "Dongguan": "CNDGG",
                               "Dalian": "CNDLC",
                               "Doumen": "CNDOU",
                               "Dalian Pt": "CNDXG",
                               "Fangcheng": "CNFAN",
                               "Fuzhou": "CNFOC",
                               "Foshan": "CNFOS",
                               "Foshan New Port": "CNFRT",
                               "Fuzhou": "CNFZH",
                               "Gaosha": "CNGAS",
                               "Guangzhou": "CNGGZ",
                               "Gaolan": "CNGLN",
                               "Gaoming": "CNGOM",
                               "Gaolan": "CNGON",
                               "Haikou": "CNHAK",
                               "Heshan": "CNHAS",
                               "Hefei": "CNHFE",
                               "Hongwan": "CNHGW",
                               "Haikou": "CNHKO",
                               "Huangpu Old Port": "CNHOP",
                               "Heshan": "CNHSN",
                               "Huangpu": "CNHUA",
                               "Huangpu New Port": "CNHUN",
                               "Jiaxing": "CNJAX",
                               "Jiangyin": "CNJGY",
                               "Jingzhou": "CNJGZ",
                               "Jiangyin Pt": "CNJIA",
                               "Jiujiang": "CNJIU",
                               "Jiujiang": "CNJJG",
                               "Jiangmen": "CNJMN",
                               "Jiao Xin": "CNJXN",
                               "Nanchang": "CNKHN",
                               "Lianhuashan": "CNLIH",
                               "Lanshi": "CNLSI",
                               "Leliu": "CNLUU",
                               "Lianyungang": "CNLYG",
                               "Luzhou": "CNLZU",
                               "Mafang": "CNMFG",
                               "Mawan": "CNMWN",
                               "Nanhai": "CNNAH",
                               "Ningbo Pt": "CNNBG",
                               "Ningbo": "CNNBO",
                               "Ningde": "CNNDE",
                               "Ningbo": "CNNGB",
                               "Nangang": "CNNGG",
                               "Wuhan": "CNNHN",
                               "Nanjing": "CNNJI",
                               "Nanjing Pt": "CNNJP",
                               "Nanjing": "CNNKG",
                               "Nanning": "CNNNG",
                               "Nansha New Pt": "CNNNP",
                               "Nansha": "CNNSA",
                               "Nantong": "CNNTG",
                               "Qingdao Pt": "CNQDP",
                               "Qingyuan": "CNQYN",
                               "Qinzhou": "CNQZH",
                               "Quanzhou": "CNQZJ",
                               "Rongqi": "CNROQ",
                               "Rugao": "CNRUG",
                               "Rizhao": "CNRZH",
                               "Sanbu": "CNSBU",
                               "Shuidong": "CNSDG",
                               "Shanghai": "CNSGH",
                               "Shanghai Pt": "CNSGP",
                               "Shanghai": "CNSHA",
                               "Shenyang": "CNSHE",
                               "Sanshan": "CNSHG",
                               "Shekou": "CNSHK",
                               "Sihuimafang": "CNSHM",
                               "Qinhuangdao": "CNSHP",
                               "Sanshui": "CNSJQ",
                               "Shenwan": "CNSNW",
                               "Shantou Pt": "CNSTG",
                               "Shatian": "CNSTI",
                               "Shunde": "CNSUD",
                               "Suzhou": "CNSUH",
                               "Suzhou": "CNSUZ",
                               "Shantou": "CNSWA",
                               "Suzhou": "CNSZH",
                               "Shenzhen Pt": "CNSZP",
                               "Shenzhen": "CNSZX",
                               "Taicang": "CNTAC",
                               "Taicang": "CNTAG",
                               "Qingdao": "CNTAO",
                               "Taizhou Pt": "CNTAZ",
                               "Taishan": "CNTIS",
                               "Tianjin Pt": "CNTJP",
                               "Tianjin": "CNTNJ",
                               "Tianjin": "CNTSN",
                               "Tianjinxingang": "CNTXG",
                               "Taizhou": "CNTZO",
                               "Taizhou": "CNTZU",
                               "Waihai": "CNWAI",
                               "Weihai": "CNWEI",
                               "Waigaoqiao": "CNWGQ",
                               "Wuhan Pt": "CNWHG",
                               "Wuhu": "CNWHI",
                               "Wenzhou": "CNWNZ",
                               "Wuhan": "CNWUH",
                               "Wuzhou": "CNWUZ",
                               "Wenzhou Pt": "CNWZP",
                               "Xiamen": "CNXAM",
                               "Xiaolan": "CNXAO",
                               "Xingang": "CNXGA",
                               "Xingang": "CNXGG",
                               "Xian": "CNXIA",
                               "Xiaolan": "CNXIL",
                               "Xinhui": "CNXIN",
                               "Xingang": "CNXIP",
                               "Xintang": "CNXIT",
                               "Xiamen Haicang": "CNXMH",
                               "Xiamen": "CNXMN",
                               "Yangshan": "CNYAN",
                               "Yantai": "CNYAT",
                               "Yichang": "CNYIC",
                               "Yingkou": "CNYIK",
                               "Yiwu": "CNYIW",
                               "Yunfu": "CNYNF",
                               "Yantai": "CNYNT",
                               "Yangpu": "CNYPG",
                               "Beijiao": "CNYQS",
                               "Yantian": "CNYTN",
                               "Yantai Pt": "CNYTP",
                               "Yunfu": "CNYUF",
                               "Yueyang": "CNYUY",
                               "Yangzhou": "CNYZH",
                               "Zhuanghe": "CNZAH",
                               "Zhapu": "CNZAP",
                               "Zhanjiang": "CNZHA",
                               "Zhenjiang": "CNZHE",
                               "Zhangjiagang": "CNZJG",
                               "Zhoushan": "CNZOS",
                               "Zhapu": "CNZPU",
                               "Zhaoqing": "CNZQG",
                               "Zhongshan": "CNZSN",
                               "Zhuhai": "CNZUH",
                               "Arica": "COACM",
                               "San Andres Island": "COADZ",
                               "Barranquilla": "COBAQ",
                               "Buenaventura": "COBUN",
                               "Cartagena": "COCTG",
                               "Barrancabermeja": "COEJA",
                               "Puerto Bolivar": "COPBO",
                               "Puerto Carreno": "COPCR",
                               "Santa Marta": "COSMR",
                               "Turbo": "COTRB",
                               "Caldera": "CRCAL",
                               "Puerto Limon": "CRLIO",
                               "Moin": "CRMOB",
                               "Puntarenas": "CRPAS",
                               "Puerto Moin": "CRPMN",
                               "Puerto Caldera": "CRPTC",
                               "San Jose": "CRSJO",
                               "La Habana": "CUHAV",
                               "Mariel": "CUMAR",
                               "Moa": "CUMOA",
                               "Santiago de Cuba": "CUSCU",
                               "Mindelo": "CVMIN",
                               "Palmeira": "CVPAL",
                               "Praia": "CVRAI",
                               "Sal Rei": "CVSAR",
                               "Sao Vicente": "CVVXE",
                               "Curacao": "CWCUR",
                               "Willemstad": "CWWIL",
                               "Famagusta": "CYFMG",
                               "Limassol": "CYLMS",
                               "Brake": "DEBKE",
                               "Bremen": "DEBRE",
                               "Bremerhaven": "DEBRV",
                               "Colbe": "DECBE",
                               "Cuxhaven": "DECUX",
                               "Duisburg": "DEDUI",
                               "Hamburg": "DEHAM",
                               "Hof": "DEHXF",
                               "Kamen": "DEKMN",
                               "Lubeck": "DELBC",
                               "Travemunde": "DETRV",
                               "Tuttlingen": "DETUT",
                               "Wilhelmshaven": "DEWVN",
                               "Djibouti": "DJJIB",
                               "Djibouti": "DJPOD",
                               "Aalborg": "DKAAL",
                               "Aarhus": "DKAAR",
                               "Kobenhavn": "DKCPH",
                               "Esbjerg": "DKEBJ",
                               "Fredericia": "DKFRC",
                               "Glostrup": "DKGLS",
                               "Hanstholm": "DKHAN",
                               "Hirtshals": "DKHIR",
                               "Kalundborg": "DKKAL",
                               "Nyborg": "DKNBG",
                               "Odense": "DKODE",
                               "Skagen": "DKSKA",
                               "Skanderborg": "DKSKG",
                               "Skovshoved": "DKSKH",
                               "Tastrup": "DKTAA",
                               "Thisted": "DKTED",
                               "Thyboron": "DKTHN",
                               "Belfast": "DMBEL",
                               "Roseau": "DMRSU",
                               "Caucedo": "DOCAU",
                               "Rio Haina": "DOHAI",
                               "Manzanillo": "DOMAN",
                               "Puerto Plata": "DOPOP",
                               "Santo Domingo": "DOSDQ",
                               "Oran Dry Port": "DZ2ON",
                               "Annaba (ex Bone)": "DZAAE",
                               "Alger (Algiers)": "DZALG",
                               "Arzew": "DZAZW",
                               "Bejaia (ex Bougie)": "DZBJA",
                               "Djen-Djen": "DZDJE",
                               "Ghazaouet": "DZGHZ",
                               "Mostaganem": "DZMOS",
                               "Oran": "DZORN",
                               "Rouiba": "DZROU",
                               "Skikda (ex Philippeville)": "DZSKI",
                               "Esmeraldas": "ECESM",
                               "Guayaquil": "ECGYE",
                               "Guayaquil": "ECGYQ",
                               "Manta": "ECMEC",
                               "Puerto Bolivar": "ECPBO",
                               "Posorja": "ECPSJ",
                               "Muuga": "EEMUG",
                               "Muuga": "EEMUU",
                               "Paldiski Lounasadam": "EEPLS",
                               "Sillamae": "EESLM",
                               "Tallinn": "EETLL",
                               "Al Adabiyah": "EGADA",
                               "Ain Sukhna": "EGAIS",
                               "Alexandria": "EGALX",
                               "El Iskandariya": "EGALY",
                               "Dumyat (Damietta)": "EGDAM",
                               "El Dekheila": "EGEDK",
                               "Hamrawein": "EGHAM",
                               "Port Said": "EGPSD",
                               "Port Said East": "EGPSE",
                               "Port Said West": "EGPSW",
                               "Sokhna Port": "EGSOK",
                               "El Suweis": "EGSUZ",
                               "Massawa (Mitsiwa)": "ERMSW",
                               "Lanzarote": "ESACE",
                               "Malaga": "ESAGP",
                               "Alicante": "ESALC",
                               "Algeciras": "ESALG",
                               "Barcelona": "ESBCN",
                               "Bilbao": "ESBIO",
                               "Cadiz": "ESCAD",
                               "Cartagena": "ESCAR",
                               "Castellon de la Plana": "ESCAS",
                               "Ceuta": "ESCEU",
                               "Ferrol": "ESFRO",
                               "Puerto del Rosario-Fuerteventura": "ESFUE",
                               "Gijon": "ESGIJ",
                               "Huelva": "ESHUV",
                               "Ibiza": "ESIBZ",
                               "Almeria": "ESLEI",
                               "Las Palmas de Gran Canaria": "ESLPA",
                               "Melilla": "ESMLN",
                               "Marin": "ESMPG",
                               "Palma de Mallorca": "ESPMI",
                               "Puerto Rosario": "ESPRO",
                               "San Antonio": "ESSAA",
                               "Sagunto": "ESSAG",
                               "Santa Cruz de Tenerife": "ESSCT",
                               "Santander": "ESSDR",
                               "Santurce": "ESSNR",
                               "Santa Cruz de La Palma": "ESSPC",
                               "Sevilla": "ESSVQ",
                               "Tarragona": "ESTAR",
                               "Vigo": "ESVGO",
                               "Villagarcia de Arosa": "ESVIL",
                               "Valencia": "ESVLC",
                               "Zaragoza": "ESZAZ",
                               "Espoo (Esbo)": "FIESP",
                               "Helsingfors (Helsinki)": "FIHEL",
                               "Hango (Hanko)": "FIHKO",
                               "Fredrikshamn (Hamina)": "FIHMN",
                               "Imatra": "FIIMA",
                               "Kemi/Tornio (Kemi/Tornea)": "FIKEM",
                               "Karleby (Kokkola)": "FIKOK",
                               "Kotka": "FIKTK",
                               "Mantyluoto": "FIMTY",
                               "Nadendal (Naantali)": "FINLI",
                               "Uleaborg (Oulu)": "FIOUL",
                               "Pori (Bjorneborg)": "FIPOR",
                               "Raahe (Brahestad)": "FIRAA",
                               "Raumo (Rauma)": "FIRAU",
                               "Abo (Turku)": "FITKU",
                               "Tornio (Tornea)": "FITOR",
                               "Lautoka": "FJLTK",
                               "Suva": "FJSUV",
                               "Mount Pleasant": "FKMPN",
                               "Pohnpei (ex Ponape)": "FMPNI",
                               "Chuuk (ex Truk)": "FMTKK",
                               "Yap": "FMYAP",
                               "Kollafjordur": "FOKOL",
                               "Klaksvik": "FOKVI",
                               "Runavik": "FORVK",
                               "Thorshavn": "FOTHO",
                               "Bassens": "FRBAS",
                               "Brest": "FRBES",
                               "Bordeaux": "FRBOD",
                               "Calais": "FRCQF",
                               "Dunkerque": "FRDKK",
                               "Fos-sur-Mer": "FRFOS",
                               "Harnes": "FRHRN",
                               "Dunkirk": "FRIRK",
                               "Le Havre": "FRLEH",
                               "La Rochelle": "FRLRH",
                               "Le Verdon-sur-Mer": "FRLVE",
                               "Marseille": "FRMRS",
                               "Montoir-de-Bretagne": "FRMTX",
                               "Malaunay": "FRMUA",
                               "Radicatel": "FRRAD",
                               "Sete": "FRSET",
                               "Toulouse": "FRTLS",
                               "Rouen": "FRURO",
                               "Libreville": "GALBV",
                               "Port Gentil": "GAPOG",
                               "Aberdeen": "GBABD",
                               "Avonmouth": "GBAVO",
                               "Belfast": "GBBEL",
                               "Blackburn": "GBBLB",
                               "Bristol": "GBBRS",
                               "Coventry": "GBCVT",
                               "Cairnryan": "GBCYN",
                               "Durham": "GBDRH",
                               "Dover": "GBDVR",
                               "Folkestone": "GBFOL",
                               "Felixstowe": "GBFXT",
                               "Glasgow": "GBGLW",
                               "Grangemouth": "GBGRG",
                               "Greenock": "GBGRK",
                               "Grimsby": "GBGSY",
                               "Harwich": "GBHRW",
                               "Hartlepool": "GBHTP",
                               "Hull": "GBHUL",
                               "Immingham": "GBIMM",
                               "Killingholme": "GBKGH",
                               "King's Lynn": "GBKLN",
                               "Larne": "GBLAR",
                               "Leicester": "GBLCS",
                               "London Gateway Port": "GBLGP",
                               "Liverpool Bay Terminal": "GBLIB",
                               "Liverpool": "GBLIV",
                               "London": "GBLON",
                               "Marchwood": "GBMAW",
                               "Middlesbrough": "GBMID",
                               "Montrose": "GBMON",
                               "Nottingham": "GBNTG",
                               "Oakhamness": "GBOAK",
                               "Pembroke": "GBPEM",
                               "Purfleet": "GBPFT",
                               "Plymouth": "GBPLY",
                               "Portsmouth": "GBPME",
                               "Portbury": "GBPRU",
                               "Rosyth": "GBROY",
                               "Rotherham": "GBRTH",
                               "Scunthorpe": "GBSCP",
                               "Scrabster": "GBSCR",
                               "Sheerness": "GBSHS",
                               "St Helens": "GBSHY",
                               "Stoke on Trent": "GBSOT",
                               "Southampton": "GBSOU",
                               "South Shields": "GBSSH",
                               "Stranraer": "GBSTR",
                               "Swanmore": "GBSWM",
                               "Teesport": "GBTEE",
                               "Thamesport": "GBTHP",
                               "Tilbury": "GBTIL",
                               "Tyne": "GBTYN",
                               "Warrington": "GBWRN",
                               "Weston-Super-Mare": "GBWSM",
                               "Saint George's": "GDSTG",
                               "Batumi": "GEBUS",
                               "Poti": "GEPTI",
                               "Degrad des Cannes": "GFDDC",
                               "Accra": "GHACC",
                               "Tema": "GHTEM",
                               "Takoradi": "GHTKD",
                               "Gibraltar": "GIGIB",
                               "Sisimiut (Holsteinsborg)": "GLJHS",
                               "Banjul": "GMBJL",
                               "Conakry": "GNCKY",
                               "Port-Kamsar": "GNKMR",
                               "Basse-Terre": "GPBBR",
                               "Gustavia": "GPGUS",
                               "Port-Louis": "GPPTL",
                               "Pointe-a-Pitre": "GPPTP",
                               "Saint Barthelemy": "GPSBH",
                               "Bata": "GQBSG",
                               "Luba": "GQLUB",
                               "Malabo": "GQSSG",
                               "Athinai": "GRATH",
                               "Iraklion (Heraklion)": "GRHER",
                               "Lavrion (Laurium)": "GRLAV",
                               "Piraeus": "GRPIR",
                               "Rhodes": "GRRHO",
                               "Thessaloniki": "GRSKG",
                               "Volos": "GRVOL",
                               "Santo Tomas de Castilla": "GTIZ4",
                               "Puerto Barrios": "GTPBR",
                               "Puerto Quetzal": "GTPRQ",
                               "Puerto Santo Tomas de Castilla": "GTSTC",
                               "Guam": "GUGUM",
                               "Bissau": "GWOXB",
                               "Georgetown": "GYGEO",
                               "Hong Kong": "HKHKG",
                               "Puerto Castilla": "HNPCA",
                               "Puerto Cortes": "HNPCR",
                               "Roatan": "HNRTB",
                               "San Pedro Sula": "HNSAP",
                               "San Lorenzo": "HNSLO",
                               "Tegucigalpa": "HNTGU",
                               "Dubrovnik": "HRDBV",
                               "Kanfanar": "HRKFR",
                               "Ploce": "HRPLE",
                               "Privlaka": "HRPVK",
                               "Rijeka": "HRRJK",
                               "Split": "HRSPU",
                               "Susak": "HRSUS",
                               "Umag": "HRUMG",
                               "Cap-Haitien": "HTCAP",
                               "Laffiteau": "HTLFF",
                               "Port-au-Prince": "HTPAP",
                               "Budapest": "HUBUD",
                               "Paty": "HUPTY",
                               "Banjarmasin": "IDBDJ",
                               "Benete": "IDBEN",
                               "Bitung": "IDBIT",
                               "Belawan": "IDBLW",
                               "Benoa": "IDBOA",
                               "Balikpapan": "IDBPN",
                               "Batam (ex Batu Besar)": "IDBTH",
                               "Batam Island": "IDBTM",
                               "Jambi": "IDDJB",
                               "Jakarta": "IDJKT",
                               "Kualatanjung": "IDKTJ",
                               "Luwuk": "IDLUW",
                               "Makassar": "IDMAK",
                               "Medan": "IDMES",
                               "Merauke": "IDMKQ",
                               "Merak": "IDMRK",
                               "Ogan Komering Hilir": "IDOKH",
                               "Palu": "IDPAL",
                               "Padang": "IDPDG",
                               "Panjang (Lampung": "IDPJG",
                               "Palembang": "IDPLM",
                               "Panjang": "IDPNJ",
                               "Pontianak": "IDPNK",
                               "Perawang": "IDPWG",
                               "Semarang": "IDSRG",
                               "Samarinda": "IDSRI",
                               "Surabaya": "IDSUB",
                               "Teluk Betung": "IDTBG",
                               "Tanjungperak": "IDTJP",
                               "Timika": "IDTMK",
                               "Tanjung Priok": "IDTPP",
                               "Tebingtinggi": "IDTTI",
                               "Tual": "IDTUA",
                               "Jakarta UTC1": "IDUTC",
                               "Jakarta UTC3": "IDUTE",
                               "Belfast": "IEBEF",
                               "Dundalk": "IEDDK",
                               "Dublin-Dublin Ferryport Terminals": "IEDFT",
                               "Dublin": "IEDUB",
                               "Cork": "IEORK",
                               "Ringaskiddy Deepwater Terminal": "IERDT",
                               "Ringaskiddy": "IERIN",
                               "Rosslare": "IEROE",
                               "Waterford": "IEWAT",
                               "Ashdod": "ILASH",
                               "Ashdod Southport": "ILAST",
                               "Elat (Eilath)": "ILETH",
                               "Haifa Bayport": "ILHBT",
                               "Haifa": "ILHFA",
                               "Haifa Israel Shipyards Port": "ILMSP",
                               "Banddar": "INBND",
                               "Mumbai (ex Bombay)": "INBOM",
                               "Kolkata (ex Calcutta)": "INCCU",
                               "Cochin": "INCOK",
                               "Daman": "INDAM",
                               "Dhamra Port": "INDMQ",
                               "Ennore": "INENR",
                               "Haldia": "INHAL",
                               "Hazira Port/Surat": "INHZA",
                               "Hazira": "INHZR",
                               "Mangalore": "INIXE",
                               "Kandla": "INIXY",
                               "Port Jawaharlal Nehru": "INJNP",
                               "Kakinada": "INKAK",
                               "Kattupalli": "INKAT",
                               "Krishnapatnam": "INKRI",
                               "Kattupalli Port": "INKTP",
                               "Chennai (ex Madras)": "INMAA",
                               "Marmugao (Marmagao)": "INMRM",
                               "Mundra": "INMUN",
                               "Nhave": "INNHV",
                               "New Mangalore": "INNML",
                               "Nhava Sheva": "INNSA",
                               "Pipavav (Victor) Port": "INPAV",
                               "Port Pipavav": "INPPV",
                               "Sahnewal": "INSWA",
                               "Tuticorin": "INTUT",
                               "Visakhapatnam": "INVTZ",
                               "Diego Garcia": "IODGA",
                               "Baghdad": "IQBGW",
                               "Basra": "IQBSR",
                               "Khor al Zubair": "IQKAZ",
                               "Umm Qasr Port": "IQUQR",
                               "Asaluyeh": "IRASA",
                               "Bandar Khomeini": "IRBKM",
                               "Bandar Abbas": "IRBND",
                               "Bandar Shahid Rajaee": "IRBSR",
                               "Bushehr": "IRBUZ",
                               "Khorramshahr": "IRKHO",
                               "Akureyri": "ISAKU",
                               "Husavik - hofn": "ISHUS",
                               "Isafjordur - hofn": "ISISA",
                               "Neskaupstadur": "ISNES",
                               "Reykjavik": "ISREY",
                               "Reydarfjordur": "ISRFJ",
                               "Saudarkrokur - hofn": "ISSAU",
                               "Ancona": "ITAOI",
                               "Acerra": "ITARR",
                               "Brindisi": "ITBDS",
                               "Barletta": "ITBLT",
                               "Bari": "ITBRI",
                               "Cagliari": "ITCAG",
                               "Catania": "ITCTA",
                               "Civitavecchia": "ITCVV",
                               "Gioia Tauro": "ITGIT",
                               "Genova": "ITGOA",
                               "Livorno": "ITLIV",
                               "Leghorn": "ITLLH",
                               "Marina di Carrara": "ITMDC",
                               "Milano": "ITMIL",
                               "Napoli": "ITNAP",
                               "Palermo": "ITPMO",
                               "Pozzallo": "ITPZL",
                               "Ravenna": "ITRAN",
                               "Rome (Roma)": "ITROM",
                               "Salerno": "ITSAL",
                               "La Spezia": "ITSPE",
                               "Savona": "ITSVN",
                               "Taranto": "ITTAR",
                               "Trapani": "ITTPS",
                               "Trieste": "ITTRS",
                               "Venezia": "ITVCE",
                               "Vado Ligure": "ITVDL",
                               "Vimodrone": "ITVMD",
                               "Zenson di Piave": "ITZDP",
                               "Kingston": "JMKIN",
                               "Montego Bay": "JMMBJ",
                               "'Aqaba": "JOAQB",
                               "Al 'Aqabah": "JOAQJ",
                               "Zarka Free Zone": "JOZFZ",
                               "Aburatsu": "JPABU",
                               "Akita": "JPAXT",
                               "Chiba": "JPCHB",
                               "Fukuyama": "JPFKY",
                               "Fukuyama": "JPFYM",
                               "Hibikishinko": "JPHBK",
                               "Hachinohe": "JPHHE",
                               "Hitachinaka": "JPHIC",
                               "Hiroshima": "JPHIJ",
                               "Hakodate": "JPHKD",
                               "Hakata/Fukuoka": "JPHKT",
                               "Hamada": "JPHMD",
                               "Hososhima": "JPHSM",
                               "Hakata": "JPHTD",
                               "Ishikariwan Shinko": "JPICW",
                               "Imabari": "JPIMB",
                               "Imari": "JPIMI",
                               "Ishigaki": "JPISG",
                               "Ishikari": "JPISI",
                               "Ishikariwan": "JPISW",
                               "Iwakuni": "JPIWK",
                               "Iyomishima": "JPIYM",
                               "Kochi": "JPKCZ",
                               "Niigata": "JPKIJ",
                               "Kamaishi": "JPKIS",
                               "Kitakyushu": "JPKKJ",
                               "Kumamoto": "JPKMJ",
                               "Kanazawa": "JPKNZ",
                               "Kagoshima": "JPKOJ",
                               "Kashima": "JPKSM",
                               "Kushiro": "JPKUH",
                               "Kawasaki": "JPKWS",
                               "Maizuru": "JPMAI",
                               "Miike": "JPMII",
                               "Miike": "JPMIJ",
                               "Mizushima": "JPMIZ",
                               "Moji/Kitakyushu": "JPMOJ",
                               "Muroran": "JPMUR",
                               "Miyagi": "JPMYI",
                               "Matsuyama": "JPMYJ",
                               "Naha": "JPNAH",
                               "Nakanoseki": "JPNAN",
                               "Naoetsu": "JPNAO",
                               "Nagoya": "JPNGO",
                               "Nagasaki": "JPNGS",
                               "Nagoya": "JPNGY",
                               "Niigatahigashi": "JPNIH",
                               "Nanko": "JPNKO",
                               "NagasakiMieShikimi": "JPNMX",
                               "Oita": "JPOIT",
                               "Omaezaki": "JPOMZ",
                               "Onahama": "JPONA",
                               "Osaka": "JPOSA",
                               "Otake": "JPOTK",
                               "Otaru": "JPOTR",
                               "Sakaisenboku": "JPSBK",
                               "Shibushi": "JPSBS",
                               "Sendai": "JPSDJ",
                               "Sendaishinko": "JPSDS",
                               "Seibu": "JPSEB",
                               "Sendai": "JPSEN",
                               "Sendaishiogama": "JPSGM",
                               "Shinkiba": "JPSHK",
                               "Shimonoseki": "JPSHS",
                               "Sakaide": "JPSKD",
                               "Sakata": "JPSKT",
                               "Sakaiminato": "JPSMN",
                               "Shimizu": "JPSMZ",
                               "Takamatsu": "JPTAK",
                               "Takamatsu": "JPTAP",
                               "Tobata/Kitakyushu": "JPTBT",
                               "Toyohashi": "JPTHS",
                               "Taki": "JPTKI",
                               "Tokushima": "JPTKS",
                               "Tokuyama": "JPTKY",
                               "Tomakomai": "JPTMK",
                               "Tamatsu": "JPTMS",
                               "Toyamashinko": "JPTOS",
                               "Toyama": "JPTOY",
                               "Tsuruga": "JPTRG",
                               "Tokyo": "JPTYO",
                               "Ube": "JPUBJ",
                               "Kobe": "JPUKB",
                               "Wakayama": "JPWAK",
                               "Yatsushiro": "JPYAT",
                               "Yokkaichi": "JPYKK",
                               "Yokohama": "JPYOK",
                               "Yokosuka": "JPYOS",
                               "Mombasa": "KEMBA",
                               "Bishkek (ex Frunze)": "KGFRU",
                               "Kampong Saom": "KHKOS",
                               "Phnom Penh": "KHPNH",
                               "Sihanoukville": "KHSCH",
                               "Tarawa": "KITRW",
                               "Longoni": "KMLOG",
                               "Mutsamudu": "KMMUT",
                               "Moroni": "KMYVA",
                               "Basseterre": "KNBAS",
                               "Chongjin": "KPCHO",
                               "Nampo": "KPNAM",
                               "Busan New Port": "KRBNP",
                               "Incheon": "KRINC",
                               "Gwangyang": "KRKAN",
                               "Pohang": "KRKPO",
                               "Kunsan": "KRKSN",
                               "Gunsan": "KRKUV",
                               "Kwangyang": "KRKWA",
                               "Masan": "KRMAS",
                               "Pyeongtaek": "KRPTK",
                               "Busan": "KRPUS",
                               "Daesan/Seosan": "KRTSN",
                               "Ulsan": "KRUSN",
                               "Kuwait": "KWKWI",
                               "Shuaiba": "KWSAA",
                               "Shuwaikh": "KWSWK",
                               "Georgetown": "KYGEC",
                               "Aktau": "KZAAU",
                               "Beirut": "LBBEY",
                               "Tripoli": "LBKYE",
                               "Castries": "LCCAS",
                               "Saint Lucia Apt": "LCSLU",
                               "Vieux Fort": "LCVIF",
                               "Colombo": "LKCMB",
                               "Monrovia": "LRMLW",
                               "Klaipeda": "LTKLJ",
                               "Riga": "LVRIX",
                               "Bingazi (Benghazi)": "LYBEN",
                               "El Choms": "LYELK",
                               "Al Khums": "LYKHO",
                               "Marsa Brega": "LYLMQ",
                               "Misurata": "LYMRA",
                               "Tripoli": "LYTIP",
                               "Tobruk": "LYTOB",
                               "Agadir": "MAAGA",
                               "Casablanca": "MACAS",
                               "Nador": "MANDR",
                               "Tanger Med": "MAPTM",
                               "Safi": "MASFI",
                               "Tangier": "MATNG",
                               "Dakhla": "MAVIL",
                               "Giurgiulesti": "MDGIU",
                               "Chisinau (ex Kishinev)": "MDKIV",
                               "Bar": "MEBAR",
                               "Antsiranana": "MGDIE",
                               "Ehoala": "MGEHL",
                               "Majunga (Mahajanga)": "MGMJN",
                               "Nosy-Be": "MGNOS",
                               "Tulear (Toliara)": "MGTLE",
                               "Tamatave (Toamasina)": "MGTMM",
                               "Toamasina": "MGTOA",
                               "Vohemar": "MGVOH",
                               "Majuro": "MHMAJ",
                               "Mopti": "MLMZI",
                               "Yangon": "MMRGN",
                               "Thilawa": "MMTLA",
                               "Ulaanbaatar": "MNULN",
                               "Macau": "MOMFM",
                               "Saipan": "MPSPN",
                               "Fort-de-France": "MQFDF",
                               "Nouadhibou": "MRNDB",
                               "Nouakchott": "MRNKC",
                               "Little Bay": "MSLTB",
                               "Malta Freeport Distripark": "MTDIS",
                               "Marsaxlokk": "MTMAR",
                               "Malta (Valletta)": "MTMLA",
                               "Marsa": "MTMSA",
                               "Port Louis": "MUPLU",
                               "Male": "MVMLE",
                               "Rangali": "MVRGI",
                               "Altamira": "MXATM",
                               "Ciudad del Carmen": "MXCME",
                               "Coatzacoalcos": "MXCOA",
                               "Ensenada": "MXESE",
                               "Guaymas": "MXGYM",
                               "Lazaro Cardenas": "MXLZC",
                               "Merida": "MXMID",
                               "Mazatlan": "MXMZT",
                               "Progreso": "MXPGO",
                               "Puerto Morelos": "MXPMS",
                               "San Lorenzo": "MXSLO",
                               "Tampico": "MXTAM",
                               "Tequixquiac": "MXTCQ",
                               "Tuxpan": "MXTUX",
                               "Veracruz": "MXVER",
                               "Manzanillo": "MXZLO",
                               "Kota Kinabalu": "MYBKI",
                               "Bintulu": "MYBTU",
                               "Bagan Luar (Butterworth)": "MYBWH",
                               "Johor Bahru": "MYJHB",
                               "Kuching": "MYKCH",
                               "Kemaman": "MYKEM",
                               "Kuantan (Tanjong Gelang)": "MYKUA",
                               "Labuan": "MYLBU",
                               "Northport/Pt Klang": "MYLPK",
                               "Muar": "MYMUA",
                               "Miri": "MYMYY",
                               "Nilai": "MYNIL",
                               "Pasir Gogok": "MYPAS",
                               "Pelabuhan Kelang": "MYPBK",
                               "Penang (Georgetown)": "MYPEN",
                               "Pasir Gudang": "MYPGU",
                               "Port Klang (Pelabuhan Klang)": "MYPKG",
                               "Sibu": "MYSBW",
                               "Sandakan": "MYSDK",
                               "Tanjung Manis": "MYTMP",
                               "Tanjung Pelepas": "MYTPP",
                               "Tawau": "MYTWU",
                               "Westport/Port Klang": "MYWSP",
                               "Port Klang (Ferry Port)": "MYXPQ",
                               "Beira": "MZBEW",
                               "Nacala": "MZMNC",
                               "Maputo": "MZMPM",
                               "Quelimane": "MZUEL",
                               "Luderitz": "NALUD",
                               "Walvis Bay": "NAWVB",
                               "Noumea": "NCNOU",
                               "Prony": "NCPNY",
                               "Niamey": "NENIM",
                               "Apapa": "NGAPP",
                               "Enugu": "NGENU",
                               "Lagos": "NGLOS",
                               "Onne": "NGONN",
                               "Port Harcourt": "NGPHC",
                               "Tincan/Lagos": "NGTIN",
                               "Corinto": "NICIO",
                               "Rama": "NIRAM",
                               "Amsterdam": "NLAMS",
                               "Bergen aan Zee": "NLBEG",
                               "Eemshaven": "NLEEM",
                               "Europoort": "NLEUR",
                               "Hoek van Holland": "NLHVH",
                               "Kampen": "NLKAM",
                               "Klundert": "NLKLU",
                               "Lelystad": "NLLEY",
                               "Moerdijk": "NLMOE",
                               "Nieuwerkerke": "NLN8W",
                               "Oss": "NLOSS",
                               "Rozenburg": "NLROZ",
                               "Rotterdam": "NLRTM",
                               "Rutten": "NLRUT",
                               "Tilburg": "NLTLB",
                               "Velsen": "NLVEL",
                               "Vlaardingen": "NLVLA",
                               "Vlissingen": "NLVLI",
                               "Vuren": "NLVRN",
                               "Velsen-Noord": "NLVSN",
                               "Wanssum": "NLWAS",
                               "Alesund": "NOAES",
                               "Agotnes": "NOAGO",
                               "Averoy": "NOAVE",
                               "Berg": "NOBER",
                               "Bergen": "NOBGO",
                               "Batsfjord": "NOBJF",
                               "Brevik": "NOBVK",
                               "Drammen": "NODRM",
                               "Egersund": "NOEGE",
                               "Finnsnes": "NOFNE",
                               "Fredrikstad": "NOFRK",
                               "Floro": "NOFRO",
                               "Fusa": "NOFUS",
                               "Gjemnes": "NOGJM",
                               "Glomfjord": "NOGLO",
                               "Halden": "NOHAL",
                               "Haugesund": "NOHAU",
                               "Hammerfest": "NOHFT",
                               "Hogset": "NOHOG",
                               "Hareid": "NOHRI",
                               "Husnes": "NOHUS",
                               "Havik": "NOHVI",
                               "Hoyanger": "NOHYR",
                               "Ikornnes": "NOIKR",
                               "Kopervik": "NOKOP",
                               "Kristiansand": "NOKRS",
                               "Kristiansund": "NOKSU",
                               "Kyrksaterora": "NOKYR",
                               "Larvik": "NOLAR",
                               "Maloy": "NOMAY",
                               "Molde": "NOMOL",
                               "Mo i Rana": "NOMQN",
                               "Moss": "NOMSS",
                               "Orkanger": "NOORK",
                               "Orsta": "NOORS",
                               "Oslo": "NOOSL",
                               "Rauma": "NORAU",
                               "Rorvik": "NORVK",
                               "Sandnes": "NOSAS",
                               "Salten": "NOSAT",
                               "Skien": "NOSKE",
                               "Stokmarknes": "NOSKN",
                               "Sortland": "NOSLX",
                               "Stord": "NOSRP",
                               "Straumen": "NOSTM",
                               "Sunndalsora": "NOSUN",
                               "Svelgen": "NOSVE",
                               "Stavanger": "NOSVG",
                               "Tananger": "NOTAE",
                               "Tromso": "NOTOS",
                               "Trondheim": "NOTRD",
                               "Nauru Island": "NRINU",
                               "Alofi": "NUALO",
                               "Niue Island": "NUIUE",
                               "Auckland": "NZAKL",
                               "Blenheim": "NZBHE",
                               "Bluff": "NZBLU",
                               "Christchurch": "NZCHC",
                               "Dunedin": "NZDUD",
                               "Invercargill": "NZIVC",
                               "Lyttelton": "NZLYT",
                               "Marsden Point": "NZMAP",
                               "Napier": "NZNPE",
                               "Port Taranaki/New Plymouth": "NZNPL",
                               "Nelson": "NZNSN",
                               "Port Chalmers": "NZPOE",
                               "Timaru": "NZTIU",
                               "Tauranga": "NZTRG",
                               "Wanganui": "NZWAG",
                               "Wellington": "NZWLG",
                               "Duqm": "OMDQM",
                               "Muscat": "OMMCT",
                               "Salalah": "OMSLL",
                               "Sohar": "OMSOH",
                               "Balboa": "PABLB",
                               "Cristobal": "PACTB",
                               "Manzanillo": "PAMIT",
                               "Colon": "PAONX",
                               "PanamÃ¡": "PAPTY",
                               "Rodman": "PAROD",
                               "Callao": "PECLL",
                               "Ilo": "PEILQ",
                               "Lima": "PELIM",
                               "Matarani": "PEMRI",
                               "Paita": "PEPAI",
                               "San Juan": "PESJA",
                               "Papeete": "PFPPT",
                               "Alotau": "PGGUR",
                               "Kimbe": "PGKIM",
                               "Lae": "PGLAE",
                               "Madang": "PGMAG",
                               "Motukea Island": "PGMTK",
                               "Port Moresby": "PGPOM",
                               "Rabaul": "PGRAB",
                               "Wewak": "PGWWK",
                               "Bauan/Batangas": "PHBAU",
                               "Batangas/Luzon": "PHBTG",
                               "Bugo": "PHBUG",
                               "Cebu": "PHCEB",
                               "Cagayan de Oro": "PHCGY",
                               "Davao": "PHDVO",
                               "General Santos": "PHGES",
                               "Port Irene": "PHIRN",
                               "Manila": "PHMNL",
                               "Manila North Harbour": "PHMNN",
                               "Manila South Harbour": "PHMNS",
                               "Panabo": "PHPAN",
                               "Sasa/Davao": "PHSAS",
                               "Subic Bay": "PHSFS",
                               "Karachi-Muhammad Bin Qasim": "PKBQM",
                               "Gwadar": "PKGWD",
                               "Karachi Container Terminal": "PKKCT",
                               "Karachi": "PKKHI",
                               "Kiamari": "PKKIA",
                               "Pakistan International Container Terminal/Karachi": "PKPCT",
                               "Port Qasim": "PKQCT",
                               "Gdynia": "PLGCT",
                               "Gdansk": "PLGDN",
                               "Gdynia": "PLGDY",
                               "Katowice": "PLKAT",
                               "Swinoujscie": "PLSWI",
                               "Szczecin": "PLSZZ",
                               "Warszawa": "PLWAW",
                               "Mayaguez": "PRMAZ",
                               "San Juan": "PRSJU",
                               "Aveiro": "PTAVE",
                               "Cais do Pico": "PTCDP",
                               "Canical": "PTCNL",
                               "Funchal": "PTFNC",
                               "Horta": "PTHOR",
                               "Leixoes": "PTLEI",
                               "Lisboa": "PTLIS",
                               "Ponta Delgada": "PTPDL",
                               "Setubal": "PTSET",
                               "Sines": "PTSIE",
                               "Terceira Island Apt": "PTTER",
                               "Koror": "PWROR",
                               "Asuncion": "PYASU",
                               "Colonia Mariano Roque Alonso": "PYMRA",
                               "Terport (San Antonio)": "PYTER",
                               "Villeta": "PYVLL",
                               "Doha": "QADOH",
                               "Hamad": "QAHMD",
                               "Mesaieed": "QAMES",
                               "Qapco": "QAQAP",
                               "Qchem": "QAQCH",
                               "Le Port": "RELPT",
                               "Port de Pointe des Galets": "REPDG",
                               "Reunion": "REREU",
                               "Bucuresti": "ROBUH",
                               "Constanta": "ROCND",
                               "Belgrade (Beograd)": "RSBEG",
                               "Nis": "RSINI",
                               "Arman (Magadan)": "RUARM",
                               "Azov": "RUAZO",
                               "Baltiysk": "RUBLT",
                               "Bronka Port": "RUBNK",
                               "Lomonosov": "RUBRK",
                               "Fish Port Terminal": "RUFPT",
                               "Kronshtadt": "RUKDT",
                               "Kaliningrad": "RUKGD",
                               "Kholmsk": "RUKHO",
                               "Korsakov": "RUKOR",
                               "Saint Petersburg (ex Leningrad)": "RULED",
                               "Novorossiysk": "RUNVS",
                               "Petropavlovsk-Kamchatskiy": "RUPKC",
                               "Ust'-Luga": "RUULU",
                               "Vanino": "RUVNN",
                               "Vladivostok": "RUVVO",
                               "Vostochnyy Port": "RUVYP",
                               "Dammam Bonded Free Zone": "SADFZ",
                               "Dhahran": "SADHA",
                               "Ad Dammam": "SADMM",
                               "Al Jubayl Industrial City": "SAJBI",
                               "Jeddah": "SAJED",
                               "Jubail": "SAJUB",
                               "King Abdullah City": "SAKAC",
                               "King Abdullah Port": "SAKAP",
                               "Makkah": "SAMAK",
                               "Riyadh Dry Port": "SARYP",
                               "Honiara": "SBHIR",
                               "Noro": "SBNOR",
                               "Mahe": "SCMAW",
                               "Port Victoria": "SCPOV",
                               "Victoria": "SCVIC",
                               "Port Sudan": "SDPZU",
                               "Ahus": "SEAHU",
                               "Goteborg": "SEGOT",
                               "Gavle": "SEGVX",
                               "Halmstad": "SEHAD",
                               "Helsingborg": "SEHEL",
                               "Karlshamn": "SEKAN",
                               "Langas": "SELA9",
                               "Lysekil": "SELYS",
                               "Malmo": "SEMMA",
                               "Norrkoping": "SENRK",
                               "Nynashamn": "SENYN",
                               "Oxelosund": "SEOXE",
                               "Pitea": "SEPIT",
                               "Sundsvall": "SESDL",
                               "Skelleftehamn": "SESKE",
                               "Sodertalje": "SESOE",
                               "Stockholm": "SESTO",
                               "Uddevalla": "SEUDD",
                               "Umea": "SEUME",
                               "Varberg": "SEVAG",
                               "Visby": "SEVBY",
                               "Vasteras": "SEVST",
                               "Wallhamn": "SEWAL",
                               "Jurong/Singapore": "SGJUR",
                               "Singapore Container Terminal": "SGSCT",
                               "Singapore": "SGSIN",
                               "Ascension": "SHASC",
                               "Koper": "SIKOP",
                               "Freetown": "SLFNA",
                               "Dakar": "SNDKR",
                               "Berbera": "SOBBO",
                               "Kismayu": "SOKMU",
                               "Mogadishu": "SOMGQ",
                               "Paramaribo": "SRPBM",
                               "Santo Antonio": "STSAA",
                               "Sao Tome Island": "STTMS",
                               "Acajutla": "SVAQJ",
                               "San Salvador": "SVSAL",
                               "Santo Tomas De Castilla": "SVSCI",
                               "Philipsburg": "SXPHI",
                               "Sint-Maarten Apt": "SXSXM",
                               "Aleppo (Alep)": "SYALP",
                               "Damascus (Damas)": "SYDAM",
                               "Homs": "SYHMS",
                               "Latakia": "SYLTK",
                               "Hama": "SYQHM",
                               "Tartus": "SYTTS",
                               "Grand Turk Island": "TCGDT",
                               "Providenciales": "TCPLS",
                               "Lome": "TGLFW",
                               "Bangkok": "THBKK",
                               "Bangkok Modern Terminals/Bangkok": "THBMT",
                               "Phra Khanong": "THKRU",
                               "Klong Toey": "THKTL",
                               "Khlong Toei": "THKTY",
                               "Laem Chabang": "THLCH",
                               "Lat Krabang": "THLKR",
                               "Siam Bangkok Port": "THSBP",
                               "Sahathai Coastal Seaport": "THSCS",
                               "Siam Container Terminal": "THSCT",
                               "Songkhla": "THSGK",
                               "Songkhla": "THSGZ",
                               "Samut Prakan Sahathai Terminal": "THSPS",
                               "Sriracha": "THSRI",
                               "Thai prosperity terminal": "THTPT",
                               "Trang Apt": "THTST",
                               "Unithai Container Terminal": "THUCT",
                               "Dushanbe": "TJDYU",
                               "Dili": "TLDIL",
                               "Ashgabat": "TMAGT",
                               "Turkmenbashi": "TMKRW",
                               "Bizerte": "TNBIZ",
                               "Rades": "TNRDS",
                               "Sfax": "TNSFA",
                               "Sousse": "TNSUS",
                               "Tunis": "TNTUN",
                               "Nuku'alofa": "TOTBU",
                               "Vava'u": "TOVAV",
                               "Aliaga": "TRALI",
                               "Ambarli": "TRAMB",
                               "Ambarli": "TRAMR",
                               "Alsancak": "TRANC",
                               "Ankara": "TRANK",
                               "Antalya": "TRAYT",
                               "Bandirma": "TRBDM",
                               "Canakkale": "TRCKZ",
                               "Derince": "TRDRC",
                               "Eskisehir": "TRESK",
                               "Evyap Port /Kocaeli": "TREYP",
                               "Gebze": "TRGEB",
                               "Gemlik": "TRGEM",
                               "Gaziantep": "TRGZT",
                               "Haydarpasa": "TRHAY",
                               "Iskenderun": "TRISK",
                               "Istanbul": "TRIST",
                               "Izmir": "TRIZM",
                               "Izmit": "TRIZT",
                               "Kabatas": "TRKBS",
                               "Korfez": "TRKFZ",
                               "Kumport": "TRKMX",
                               "Konak": "TRKN2",
                               "Limas": "TRLMA",
                               "Mardas": "TRMAD",
                               "Mersin": "TRMER",
                               "Mersin-Free Zone": "TRMFZ",
                               "Marport": "TRMPT",
                               "Nemrut Bay": "TRNEM",
                               "Pendik": "TRPEN",
                               "Samsun": "TRSSX",
                               "Carsamba Apt/Samsun": "TRSZF",
                               "Tekirdag": "TRTEK",
                               "Trabzon": "TRTZX",
                               "Yarimca": "TRYAR",
                               "Yilport": "TRYPO",
                               "Zeytinburnu": "TRZEY",
                               "Port-of-Spain": "TTPOS",
                               "Point Lisas": "TTPTS",
                               "Funafuti": "TVFUN",
                               "Keelung (Chilung)": "TWKEL",
                               "Kaohsiung": "TWKHH",
                               "Taipei": "TWTPE",
                               "Taichung": "TWTXG",
                               "Taoyuan": "TWTYN",
                               "Dar es Salaam": "TZDAR",
                               "Mtwara": "TZMYW",
                               "Pemba": "TZPMA",
                               "Tanga": "TZTGT",
                               "Zanzibar": "TZZNZ",
                               "Bar": "UABAR",
                               "Dniprovka": "UADNI",
                               "Dnepropetrovsk": "UADNK",
                               "Kyiv": "UAIEV",
                               "Illichivs'k": "UAILK",
                               "Ilyichevsk": "UAILY",
                               "Izmail": "UAIZM",
                               "L'viv": "UALVI",
                               "Odesa": "UAODS",
                               "Solomonovo": "UASLO",
                               "Yuzhny (Pivdennyi)": "UAYUZ",
                               "Kampala": "UGKLA",
                               "Anchorage": "USANC",
                               "Baltimore": "USBAL",
                               "Bayonne": "USBAY",
                               "Blount Island": "USBI8",
                               "Nashville": "USBNA",
                               "Boston": "USBOS",
                               "Brooklyn/New York": "USBOY",
                               "Charleston": "USCHS",
                               "Chester": "USCHT",
                               "Cleveland": "USCLE",
                               "Cincinnati": "USCVG",
                               "Detroit": "USDET",
                               "Dutch Harbor": "USDUT",
                               "Eddystone": "USESX",
                               "Newark": "USEWR",
                               "Fernandina Beach": "USFEB",
                               "Freeport": "USFPO",
                               "Gloucester City": "USGLC",
                               "Galveston": "USGLS",
                               "Greenport": "USGP4",
                               "Gulfport": "USGPT",
                               "Honolulu": "USHNL",
                               "Houston": "USHOU",
                               "Wilmington": "USILG",
                               "Wilmington": "USILM",
                               "Hilo": "USITO",
                               "Jacksonville": "USJAX",
                               "Kansas City": "USKCK",
                               "Kawaihae": "USKWH",
                               "Los Angeles": "USLAX",
                               "Long Beach": "USLGB",
                               "Louisville": "USLUI",
                               "Memphis": "USMEM",
                               "Miami": "USMIA",
                               "Kansas City": "USMKC",
                               "Mobile": "USMOB",
                               "New Orleans": "USMSY",
                               "Nawiliwili": "USNIJ",
                               "Port Hueneme": "USNTD",
                               "North Charleston": "USNTS",
                               "New York": "USNYC",
                               "Oakland": "USOAK",
                               "Kahului": "USOGG",
                               "Omaha": "USOMA",
                               "Norfolk": "USORF",
                               "Worcester": "USORH",
                               "Palm Beach": "USPAB",
                               "Everett": "USPAE",
                               "West Palm Beach": "USPBI",
                               "Port Canaveral": "USPCV",
                               "Portland": "USPDX",
                               "Port Elizabeth": "USPEB",
                               "Port Everglades": "USPEF",
                               "Panama City": "USPFN",
                               "Philadelphia": "USPHL",
                               "Saint Petersburg": "USPIE",
                               "Port Manatee": "USPME",
                               "Pennsauken": "USPPS",
                               "Portsmouth": "USPSM",
                               "Portsmouth": "USPTM",
                               "Portland": "USPWM",
                               "San Diego": "USSAN",
                               "Savannah": "USSAV",
                               "Seattle": "USSEA",
                               "San Francisco": "USSFO",
                               "South Haven": "USSOH",
                               "San Pedro": "USSPQ",
                               "Saint Louis": "USSTL",
                               "Tacoma": "USTIW",
                               "Tampa": "USTPA",
                               "Savannah": "USTSA",
                               "Vancouver": "USVAN",
                               "Freeport": "USXAS",
                               "Montevideo": "UYMVD",
                               "Tashkent": "UZTAS",
                               "Campden Park": "VCCRP",
                               "Kingstown": "VCKTN",
                               "El Guamache": "VEEGU",
                               "Guaranao": "VEGUA",
                               "Guaranao Bay": "VEGUB",
                               "Guanta": "VEGUT",
                               "La Guaira": "VELAG",
                               "Maracaibo": "VEMAR",
                               "Matanzas": "VEMTV",
                               "Puerto Cabello": "VEPBL",
                               "Road Town": "VGRAD",
                               "Tortola": "VGTOV",
                               "Virgin Gorda": "VGVIJ",
                               "Charlotte Amalie": "VICHA",
                               "Christiansted": "VICTD",
                               "Saint Thomas": "VISTT",
                               "Binh Duong": "VNBDU",
                               "Chu Lai": "VNC8Q",
                               "Cat Lai": "VNCLI",
                               "Cai Lan": "VNCLN",
                               "Cai Mep International Terminal": "VNCMT",
                               "Da Nang": "VNDAD",
                               "Dong Nai": "VNDNA",
                               "Tien Sa Terminal": "VNDTS",
                               "Hanoi": "VNHAN",
                               "Haiphong": "VNHPH",
                               "Tan Cang Hiep Phuoc Port": "VNHPP",
                               "Phuoc Long ICD": "VNIPH",
                               "Thu Duc/ICG Transimex": "VNITX",
                               "Lach Huyen Pt Haiphong": "VNLAH",
                               "Nghi Son": "VNNGH",
                               "Nha Trang": "VNNHA",
                               "Cat Lai Oil Port": "VNOCL",
                               "Phuoc Long": "VNPHG",
                               "Ho Chi Minh City": "VNSGN",
                               "Hiep Phuoc Port": "VNSPC",
                               "SP-SSA International Terminal (SSIT)": "VNSPT",
                               "ICD Sotrans": "VNSTR",
                               "Tanamexco ICD": "VNTAM",
                               "Tan Cang": "VNTCG",
                               "Tan Cang - Cai Mep Terminal": "VNTCT",
                               "Cai Mep": "VNTOT",
                               "Qui Nhon": "VNUIH",
                               "Can Tho": "VNVCA",
                               "Vung Tau": "VNVUT",
                               "Santo": "VUSAN",
                               "Port Vila": "VUVLI",
                               "Mata'utu": "WFMAU",
                               "Apia": "WSAPW",
                               "Aden": "YEADE",
                               "Hodeidah": "YEHOD",
                               "Mukalla": "YEMKX",
                               "Longoni": "YTLON",
                               "Cape Town": "ZACPT",
                               "Eastern Cape": "ZACTP",
                               "Durban": "ZADUR",
                               "East London": "ZAELS",
                               "Port of Ngqura": "ZANGQ",
                               "Port Elizabeth": "ZAPLZ",
                               "Coega": "ZAZBA",
                               "Harare": "ZWHRE"}
